/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCreateAccountRouteImport } from './routes/_authenticated/create-account'
import { Route as AuthenticatedCreateAlertRouteImport } from './routes/_authenticated/create-alert'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateAccountRoute =
  AuthenticatedCreateAccountRouteImport.update({
    id: '/create-account',
    path: '/create-account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreateAlertRoute =
  AuthenticatedCreateAlertRouteImport.update({
    id: '/create-alert',
    path: '/create-alert',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/create-account': typeof AuthenticatedCreateAccountRoute
  '/create-alert': typeof AuthenticatedCreateAlertRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/create-account': typeof AuthenticatedCreateAccountRoute
  '/create-alert': typeof AuthenticatedCreateAlertRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/create-account': typeof AuthenticatedCreateAccountRoute
  '/_authenticated/create-alert': typeof AuthenticatedCreateAlertRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/setup' | '/sign-in' | '/create-account' | '/create-alert'
  fileRoutesByTo: FileRoutesByTo
  to: '/setup' | '/sign-in' | '/create-account' | '/create-alert' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/setup'
    | '/sign-in'
    | '/_authenticated/create-account'
    | '/_authenticated/create-alert'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-account': {
      id: '/_authenticated/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof AuthenticatedCreateAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-alert': {
      id: '/_authenticated/create-alert'
      path: '/create-alert'
      fullPath: '/create-alert'
      preLoaderRoute: typeof AuthenticatedCreateAlertRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCreateAccountRoute: typeof AuthenticatedCreateAccountRoute
  AuthenticatedCreateAlertRoute: typeof AuthenticatedCreateAlertRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreateAccountRoute: AuthenticatedCreateAccountRoute,
  AuthenticatedCreateAlertRoute: AuthenticatedCreateAlertRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
